### ISSUE TITLE
feature req: build_data file from builds

### ISSUE THREAD

**Issue by jupe** [ARMmbed/mbed-cli#264]
I'm building application which support multiple targets, all toolchains and different configurations depend on target. Now only way get all binaries is to build with `mbed --output..`  -option which place binaries to different subfolders, but more hard is to fetch all builds details to one place.

If mbed-cli could provide some kind of build json file to root folder which contains same kind of information than `test_spec.json` file it would be much better. This file should describe at least target, sizes, configuration, compiler flags, binary relative location, toolchain, compiler version, module versions (sha/tag), mbed-cli version, ...
This file could be then used by CI for example show some graphs that how build sizes is changed during developing cycles. Also flash tool could select binary using this file. Actually I'm quite sure that we could even combine `test_spec.json` file with this in the end, because it provide almost identical information in different format...

File format could be something like this:

```
{
mbed-cli: <version>,
builds: [
  {
    duration: <seconds>,
    toochain: {
        name: <toolchain>,
        version: <version>
    },
    mbed_os: {
        version: <string>,
        git_commitId: <commitId>,
        clean: <boolean: true if no local mods>
    },
    target: {
         name: <target-device-name>, 
         core: <target core>
    },
    location: <relative-path>,
    memap_ref: <memap-relative-path>,
    libraries: [{
         name: <lib name>,
         version: <string, if relevant>,
         git_commitId: <lib commit id>,
         clean: <boolean: true if no local mods>
    }],
    compiler: {
          macros: []  
          flags: [],
    },
    linker: {
       flags: []
    },
    configuration: {
          name: <application-json-file-name>,
          ref: <relative-path>
    },
    ... 
  }
]
```

## Todo
* [x] build data collection ([PR](https://github.com/ARMmbed/mbed-os/pull/4110#issuecomment-296207128)  merged)
* [ ] extend with git details
* [ ] integrate all details to elf file with custom section

**Comment by jupe** [comment]
@theotherjimmy any news ?

**Comment by theotherjimmy** [comment]
`duration`, `toolchain`, `target`, `location`, `memmap-ref`, `compiler` (`compiler-c` and `compiler-c++`), `linker`, and `configuration` must all come from mbed-os tooling.

**Comment by theotherjimmy** [comment]
@jupe Making progress by extending what gets written to test_spec.json and writing the same info on a build. Here's an example.
```json
{
    "K64F": {
        "GCC_ARM": {
            "MBED-OS-EXAMPLE-FAT-FILESYSTEM": [
                {
                    "0": {
                        "linker": {
                            "flags": [
                                "-Wl,--gc-sections",
                                "-Wl,--wrap,main",
                                "-Wl,--wrap,_malloc_r",
                                "-Wl,--wrap,_free_r",
                                "-Wl,--wrap,_realloc_r",
                                "-Wl,--wrap,_calloc_r",
                                "-Wl,--wrap,exit",
                                "-Wl,--wrap,atexit",
                                "-mcpu=cortex-m4",
                                "-mthumb",
                                "-mfpu=fpv4-sp-d16",
                                "-mfloat-abi=softfp"
                            ]
                        },
                        "description": "mbed-os-example-fat-filesystem",
                        "library_configs": [
                            "mbed-os/rtos/mbed_lib.json",
                            "mbed-os/events/mbed_lib.json",
                            "mbed-os/features/FEATURE_LWIP/lwip-interface/mbed_lib.json",
                            "mbed-os/features/filesystem/mbed_lib.json",
                            "mbed-os/features/storage/FEATURE_STORAGE/cfstore/mbed_lib.json",
                            "mbed-os/features/frameworks/utest/mbed_lib.json",
                            "mbed-os/platform/mbed_lib.json",
                            "mbed-os/features/netsocket/mbed_lib.json"
                        ],
                        "target_name": "K64F",
                        "assembler": {
                            "symbols": [
                                "__CORTEX_M4",
                                "CPU_MK64FN1M0VMD12",
                                "ARM_MATH_CM4",
                                "__FPU_PRESENT=1",
                                "__MBED_CMSIS_RTOS_CM",
                                "__CMSIS_RTOS",
                                "FSL_RTOS_MBED"
                            ],
                            "flags": [
                                "-x",
                                "assembler-with-cpp"
                            ]
                        },
                        "elf": "./BUILD/K64F/gcc_arm/mbed-os-example-fat-filesystem.bin",
                        "cxx_compiler": {
                            "symbols": [
                                "FEATURE_LWIP=1",
                                "__MBED__=1",
                                "DEVICE_I2CSLAVE=1",
                                "__FPU_PRESENT=1",
                                "TARGET_Freescale",
                                "DEVICE_PORTINOUT=1",
                                "TARGET_RTOS_M4_M7",
                                "DEVICE_LOWPOWERTIMER=1",
                                "DEVICE_RTC=1",
                                "TOOLCHAIN_object",
                                "DEVICE_SERIAL_ASYNCH=1",
                                "__CMSIS_RTOS",
                                "FSL_RTOS_MBED",
                                "DEVICE_STORAGE=1",
                                "TARGET_KPSDK_MCUS",
                                "TARGET_FLASH_CMSIS_ALGO",
                                "TOOLCHAIN_GCC",
                                "ARM_MATH_CM4",
                                "TARGET_KSDK2_MCUS",
                                "TARGET_LIKE_CORTEX_M4",
                                "DEVICE_ANALOGOUT=1",
                                "TARGET_M4",
                                "TARGET_UVISOR_UNSUPPORTED",
                                "TARGET_K64F",
                                "DEVICE_SPI_ASYNCH=1",
                                "DEVICE_PWMOUT=1",
                                "DEVICE_INTERRUPTIN=1",
                                "DEVICE_I2C=1",
                                "DEVICE_PORTOUT=1",
                                "__CORTEX_M4",
                                "DEVICE_STDIO_MESSAGES=1",
                                "CPU_MK64FN1M0VMD12",
                                "TARGET_LIKE_MBED",
                                "TARGET_FF_ARDUINO",
                                "TARGET_KPSDK_CODE",
                                "TARGET_RELEASE",
                                "DEVICE_SERIAL_FC=1",
                                "DEVICE_FLASH=1",
                                "DEVICE_TRNG=1",
                                "__MBED_CMSIS_RTOS_CM",
                                "DEVICE_SLEEP=1",
                                "TOOLCHAIN_GCC_ARM",
                                "TARGET_FRDM",
                                "TARGET_MCUXpresso_MCUS",
                                "DEVICE_SPI=1",
                                "FEATURE_STORAGE=1",
                                "DEVICE_ERROR_RED=1",
                                "DEVICE_SPISLAVE=1",
                                "DEVICE_ANALOGIN=1",
                                "DEVICE_SERIAL=1",
                                "MBED_BUILD_TIMESTAMP=1488229859.37",
                                "DEVICE_PORTIN=1",
                                "TARGET_MCU_K64F",
                                "TARGET_CORTEX_M"
                            ],
                            "flags": [
                                "-std=gnu++98",
                                "-fno-rtti",
                                "-Wvla"
                            ]
                        },
                        "elapsed_time": 0.14609694480895996,
                        "c_compiler": {
                            "symbols": [
                                "FEATURE_LWIP=1",
                                "__MBED__=1",
                                "DEVICE_I2CSLAVE=1",
                                "__FPU_PRESENT=1",
                                "TARGET_Freescale",
                                "DEVICE_PORTINOUT=1",
                                "TARGET_RTOS_M4_M7",
                                "DEVICE_LOWPOWERTIMER=1",
                                "DEVICE_RTC=1",
                                "TOOLCHAIN_object",
                                "DEVICE_SERIAL_ASYNCH=1",
                                "__CMSIS_RTOS",
                                "FSL_RTOS_MBED",
                                "DEVICE_STORAGE=1",
                                "TARGET_KPSDK_MCUS",
                                "TARGET_FLASH_CMSIS_ALGO",
                                "TOOLCHAIN_GCC",
                                "ARM_MATH_CM4",
                                "TARGET_KSDK2_MCUS",
                                "TARGET_LIKE_CORTEX_M4",
                                "DEVICE_ANALOGOUT=1",
                                "TARGET_M4",
                                "TARGET_UVISOR_UNSUPPORTED",
                                "TARGET_K64F",
                                "DEVICE_SPI_ASYNCH=1",
                                "DEVICE_PWMOUT=1",
                                "DEVICE_INTERRUPTIN=1",
                                "DEVICE_I2C=1",
                                "DEVICE_PORTOUT=1",
                                "__CORTEX_M4",
                                "DEVICE_STDIO_MESSAGES=1",
                                "CPU_MK64FN1M0VMD12",
                                "TARGET_LIKE_MBED",
                                "TARGET_FF_ARDUINO",
                                "TARGET_KPSDK_CODE",
                                "TARGET_RELEASE",
                                "DEVICE_SERIAL_FC=1",
                                "DEVICE_FLASH=1",
                                "DEVICE_TRNG=1",
                                "__MBED_CMSIS_RTOS_CM",
                                "DEVICE_SLEEP=1",
                                "TOOLCHAIN_GCC_ARM",
                                "TARGET_FRDM",
                                "TARGET_MCUXpresso_MCUS",
                                "DEVICE_SPI=1",
                                "FEATURE_STORAGE=1",
                                "DEVICE_ERROR_RED=1",
                                "DEVICE_SPISLAVE=1",
                                "DEVICE_ANALOGIN=1",
                                "DEVICE_SERIAL=1",
                                "MBED_BUILD_TIMESTAMP=1488229859.37",
                                "DEVICE_PORTIN=1",
                                "TARGET_MCU_K64F",
                                "TARGET_CORTEX_M"
                            ],
                            "flags": [
                                "-std=gnu99"
                            ]
                        },
                        "app_config": "./mbed_app.json",
                        "result": "OK",
                        "toolchain_name": "GCC_ARM",
                        "output": "Building project mbed-os-example-fat-filesystem (K64F, GCC_ARM)\nScan: .\nScan: FEATURE_LWIP\nScan: FEATURE_COMMON_PAL\nScan: FEATURE_UVISOR\nScan: FEATURE_BLE\nScan: FEATURE_LOWPAN_ROUTER\nScan: FEATURE_ETHERNET_HOST\nScan: FEATURE_NANOSTACK\nScan: FEATURE_THREAD_END_DEVICE\nScan: FEATURE_THREAD_ROUTER\nScan: FEATURE_THREAD_BORDER_ROUTER\nScan: FEATURE_LOWPAN_BORDER_ROUTER\nScan: FEATURE_NANOSTACK_FULL\nScan: FEATURE_LOWPAN_HOST\nScan: FEATURE_STORAGE\nScan: mbed\nScan: env\n+--------------------------+-------+-------+-------+\n| Module                   | .text | .data |  .bss |\n+--------------------------+-------+-------+-------+\n| Fill                     |   164 |     0 |  2136 |\n| Misc                     | 54505 |  2556 |   754 |\n| drivers                  |   640 |     0 |    32 |\n| features/filesystem      | 15793 |     0 |   550 |\n| features/storage         |    42 |     0 |   184 |\n| hal                      |   418 |     0 |     8 |\n| platform                 |  2355 |    20 |   582 |\n| rtos                     |   135 |     4 |     4 |\n| rtos/rtx                 |  5861 |    20 |  6870 |\n| targets/TARGET_Freescale |  8382 |    12 |   384 |\n| Subtotals                | 88295 |  2612 | 11504 |\n+--------------------------+-------+-------+-------+\nAllocated Heap: 24576 bytes\nAllocated Stack: unknown\nTotal Static RAM memory (data + bss): 14116 bytes\nTotal RAM memory (data + bss + heap + stack): 38692 bytes\nTotal Flash memory (text + data + misc): 91947 bytes\n",
                        "id": "MBED-OS-EXAMPLE-FAT-FILESYSTEM",
                        "memory_usage": [
                            {
                                "module": "Fill",
                                "size": {
                                    ".data": 0,
                                    ".bss": 2136,
                                    ".text": 164
                                }
                            },
                            {
                                "module": "Misc",
                                "size": {
                                    ".data": 2556,
                                    ".bss": 754,
                                    ".text": 54505
                                }
                            },
                            {
                                "module": "drivers",
                                "size": {
                                    ".data": 0,
                                    ".bss": 32,
                                    ".text": 640
                                }
                            },
                            {
                                "module": "features/filesystem",
                                "size": {
                                    ".data": 0,
                                    ".bss": 550,
                                    ".text": 15793
                                }
                            },
                            {
                                "module": "features/storage",
                                "size": {
                                    ".data": 0,
                                    ".bss": 184,
                                    ".text": 42
                                }
                            },
                            {
                                "module": "hal",
                                "size": {
                                    ".data": 0,
                                    ".bss": 8,
                                    ".text": 418
                                }
                            },
                            {
                                "module": "platform",
                                "size": {
                                    ".data": 20,
                                    ".bss": 582,
                                    ".text": 2355
                                }
                            },
                            {
                                "module": "rtos",
                                "size": {
                                    ".data": 4,
                                    ".bss": 4,
                                    ".text": 135
                                }
                            },
                            {
                                "module": "rtos/rtx",
                                "size": {
                                    ".data": 20,
                                    ".bss": 6870,
                                    ".text": 5861
                                }
                            },
                            {
                                "module": "targets/TARGET_Freescale",
                                "size": {
                                    ".data": 12,
                                    ".bss": 384,
                                    ".text": 8382
                                }
                            },
                            {
                                "summary": {
                                    "total_flash": 91947,
                                    "static_ram": 14116,
                                    "stack": 0,
                                    "heap": 24576,
                                    "total_ram": 38692
                                }
                            }
                        ]
                    }
                }
            ]
        }
    }
}
```

**Comment by jupe** [comment]
is there branch/pr for this to start initial reviewing?

**Comment by theotherjimmy** [comment]
Not yet. I can push up my current modifications to my fork and we can coordinate there.

**Comment by theotherjimmy** [comment]
https://github.com/ARMmbed/mbed-os/compare/master...theotherjimmy:build-metadata

**Comment by jupe** [comment]
I would like too see more flat json with builds array (like I.propose) because then it is easier to manage.. also its then better format for db.. elf value seems to be bin file, should it be elf file instead or was it just typo?

**Comment by theotherjimmy** [comment]
That was a typo

**Comment by jupe** [comment]
ok. please add also elf file relative path in json

**Comment by theotherjimmy** [comment]
Sure :+1:. I'm also going to flatten them a bit.

**Comment by theotherjimmy** [comment]
New version:
```json
{
    "builds": [
        {
            "bin": "./BUILD/K64F/gcc_arm/mbed-os-example-fat-filesystem.bin",
            "linker": {
                "flags": [
                    "-Wl,--gc-sections",
                    "-Wl,--wrap,main",
                    "-Wl,--wrap,_malloc_r",
                    "-Wl,--wrap,_free_r",
                    "-Wl,--wrap,_realloc_r",
                    "-Wl,--wrap,_calloc_r",
                    "-Wl,--wrap,exit",
                    "-Wl,--wrap,atexit",
                    "-mcpu=cortex-m4",
                    "-mthumb",
                    "-mfpu=fpv4-sp-d16",
                    "-mfloat-abi=softfp"
                ]
            },
            "description": "mbed-os-example-fat-filesystem",
            "library_configs": [
                "mbed-os/rtos/mbed_lib.json",
                "mbed-os/events/mbed_lib.json",
                "mbed-os/features/FEATURE_LWIP/lwip-interface/mbed_lib.json",
                "mbed-os/features/filesystem/mbed_lib.json",
                "mbed-os/features/storage/FEATURE_STORAGE/cfstore/mbed_lib.json",
                "mbed-os/features/frameworks/utest/mbed_lib.json",
                "mbed-os/platform/mbed_lib.json",
                "mbed-os/features/netsocket/mbed_lib.json"
            ],
            "target_name": "K64F",
            "assembler": {
                "symbols": [
                    "__CORTEX_M4",
                    "CPU_MK64FN1M0VMD12",
                    "ARM_MATH_CM4",
                    "__FPU_PRESENT=1",
                    "__MBED_CMSIS_RTOS_CM",
                    "__CMSIS_RTOS",
                    "FSL_RTOS_MBED"
                ],
                "flags": [
                    "-x",
                    "assembler-with-cpp"
                ]
            },
            "elf": "./BUILD/K64F/gcc_arm/mbed-os-example-fat-filesystem.elf",
            "cxx_compiler": {
                "symbols": [
                    "FEATURE_LWIP=1",
                    "__MBED__=1",
                    "DEVICE_I2CSLAVE=1",
                    "__FPU_PRESENT=1",
                    "TARGET_Freescale",
                    "DEVICE_PORTINOUT=1",
                    "TARGET_RTOS_M4_M7",
                    "DEVICE_LOWPOWERTIMER=1",
                    "DEVICE_RTC=1",
                    "TOOLCHAIN_object",
                    "DEVICE_SERIAL_ASYNCH=1",
                    "__CMSIS_RTOS",
                    "FSL_RTOS_MBED",
                    "DEVICE_STORAGE=1",
                    "TARGET_KPSDK_MCUS",
                    "TARGET_FLASH_CMSIS_ALGO",
                    "TOOLCHAIN_GCC",
                    "ARM_MATH_CM4",
                    "TARGET_KSDK2_MCUS",
                    "TARGET_LIKE_CORTEX_M4",
                    "DEVICE_ANALOGOUT=1",
                    "TARGET_M4",
                    "TARGET_UVISOR_UNSUPPORTED",
                    "TARGET_K64F",
                    "DEVICE_SPI_ASYNCH=1",
                    "DEVICE_PWMOUT=1",
                    "DEVICE_INTERRUPTIN=1",
                    "DEVICE_I2C=1",
                    "DEVICE_PORTOUT=1",
                    "__CORTEX_M4",
                    "DEVICE_STDIO_MESSAGES=1",
                    "CPU_MK64FN1M0VMD12",
                    "TARGET_LIKE_MBED",
                    "TARGET_FF_ARDUINO",
                    "TARGET_KPSDK_CODE",
                    "TARGET_RELEASE",
                    "DEVICE_SERIAL_FC=1",
                    "FEATURE_STORAGE=1",
                    "DEVICE_TRNG=1",
                    "MBED_BUILD_TIMESTAMP=1488314702.81",
                    "__MBED_CMSIS_RTOS_CM",
                    "DEVICE_SLEEP=1",
                    "TOOLCHAIN_GCC_ARM",
                    "TARGET_FRDM",
                    "TARGET_MCUXpresso_MCUS",
                    "DEVICE_SPI=1",
                    "DEVICE_ERROR_RED=1",
                    "DEVICE_SPISLAVE=1",
                    "DEVICE_ANALOGIN=1",
                    "DEVICE_SERIAL=1",
                    "DEVICE_FLASH=1",
                    "DEVICE_PORTIN=1",
                    "TARGET_MCU_K64F",
                    "TARGET_CORTEX_M"
                ],
                "flags": [
                    "-std=gnu++98",
                    "-fno-rtti",
                    "-Wvla"
                ]
            },
            "elapsed_time": 0.14613795280456543,
            "c_compiler": {
                "symbols": [
                    "FEATURE_LWIP=1",
                    "__MBED__=1",
                    "DEVICE_I2CSLAVE=1",
                    "__FPU_PRESENT=1",
                    "TARGET_Freescale",
                    "DEVICE_PORTINOUT=1",
                    "TARGET_RTOS_M4_M7",
                    "DEVICE_LOWPOWERTIMER=1",
                    "DEVICE_RTC=1",
                    "TOOLCHAIN_object",
                    "DEVICE_SERIAL_ASYNCH=1",
                    "__CMSIS_RTOS",
                    "FSL_RTOS_MBED",
                    "DEVICE_STORAGE=1",
                    "TARGET_KPSDK_MCUS",
                    "TARGET_FLASH_CMSIS_ALGO",
                    "TOOLCHAIN_GCC",
                    "ARM_MATH_CM4",
                    "TARGET_KSDK2_MCUS",
                    "TARGET_LIKE_CORTEX_M4",
                    "DEVICE_ANALOGOUT=1",
                    "TARGET_M4",
                    "TARGET_UVISOR_UNSUPPORTED",
                    "TARGET_K64F",
                    "DEVICE_SPI_ASYNCH=1",
                    "DEVICE_PWMOUT=1",
                    "DEVICE_INTERRUPTIN=1",
                    "DEVICE_I2C=1",
                    "DEVICE_PORTOUT=1",
                    "__CORTEX_M4",
                    "DEVICE_STDIO_MESSAGES=1",
                    "CPU_MK64FN1M0VMD12",
                    "TARGET_LIKE_MBED",
                    "TARGET_FF_ARDUINO",
                    "TARGET_KPSDK_CODE",
                    "TARGET_RELEASE",
                    "DEVICE_SERIAL_FC=1",
                    "FEATURE_STORAGE=1",
                    "DEVICE_TRNG=1",
                    "MBED_BUILD_TIMESTAMP=1488314702.81",
                    "__MBED_CMSIS_RTOS_CM",
                    "DEVICE_SLEEP=1",
                    "TOOLCHAIN_GCC_ARM",
                    "TARGET_FRDM",
                    "TARGET_MCUXpresso_MCUS",
                    "DEVICE_SPI=1",
                    "DEVICE_ERROR_RED=1",
                    "DEVICE_SPISLAVE=1",
                    "DEVICE_ANALOGIN=1",
                    "DEVICE_SERIAL=1",
                    "DEVICE_FLASH=1",
                    "DEVICE_PORTIN=1",
                    "TARGET_MCU_K64F",
                    "TARGET_CORTEX_M"
                ],
                "flags": [
                    "-std=gnu99"
                ]
            },
            "app_config": "./mbed_app.json",
            "result": "OK",
            "toolchain_name": "GCC_ARM",
            "output": "Building project mbed-os-example-fat-filesystem (K64F, GCC_ARM)\nScan: .\nScan: FEATURE_LWIP\nScan: FEATURE_COMMON_PAL\nScan: FEATURE_UVISOR\nScan: FEATURE_BLE\nScan: FEATURE_LOWPAN_ROUTER\nScan: FEATURE_ETHERNET_HOST\nScan: FEATURE_NANOSTACK\nScan: FEATURE_THREAD_END_DEVICE\nScan: FEATURE_THREAD_ROUTER\nScan: FEATURE_THREAD_BORDER_ROUTER\nScan: FEATURE_LOWPAN_BORDER_ROUTER\nScan: FEATURE_NANOSTACK_FULL\nScan: FEATURE_LOWPAN_HOST\nScan: FEATURE_STORAGE\nScan: mbed\nScan: env\n+--------------------------+-------+-------+-------+\n| Module                   | .text | .data |  .bss |\n+--------------------------+-------+-------+-------+\n| Fill                     |   164 |     0 |  2136 |\n| Misc                     | 54505 |  2556 |   754 |\n| drivers                  |   640 |     0 |    32 |\n| features/filesystem      | 15793 |     0 |   550 |\n| features/storage         |    42 |     0 |   184 |\n| hal                      |   418 |     0 |     8 |\n| platform                 |  2355 |    20 |   582 |\n| rtos                     |   135 |     4 |     4 |\n| rtos/rtx                 |  5861 |    20 |  6870 |\n| targets/TARGET_Freescale |  8382 |    12 |   384 |\n| Subtotals                | 88295 |  2612 | 11504 |\n+--------------------------+-------+-------+-------+\nAllocated Heap: 24576 bytes\nAllocated Stack: unknown\nTotal Static RAM memory (data + bss): 14116 bytes\nTotal RAM memory (data + bss + heap + stack): 38692 bytes\nTotal Flash memory (text + data + misc): 91947 bytes\n",
            "id": "MBED-OS-EXAMPLE-FAT-FILESYSTEM",
            "memory_usage": [
                {
                    "module": "Fill",
                    "size": {
                        ".data": 0,
                        ".bss": 2136,
                        ".text": 164
                    }
                },
                {
                    "module": "Misc",
                    "size": {
                        ".data": 2556,
                        ".bss": 754,
                        ".text": 54505
                    }
                },
                {
                    "module": "drivers",
                    "size": {
                        ".data": 0,
                        ".bss": 32,
                        ".text": 640
                    }
                },
                {
                    "module": "features/filesystem",
                    "size": {
                        ".data": 0,
                        ".bss": 550,
                        ".text": 15793
                    }
                },
                {
                    "module": "features/storage",
                    "size": {
                        ".data": 0,
                        ".bss": 184,
                        ".text": 42
                    }
                },
                {
                    "module": "hal",
                    "size": {
                        ".data": 0,
                        ".bss": 8,
                        ".text": 418
                    }
                },
                {
                    "module": "platform",
                    "size": {
                        ".data": 20,
                        ".bss": 582,
                        ".text": 2355
                    }
                },
                {
                    "module": "rtos",
                    "size": {
                        ".data": 4,
                        ".bss": 4,
                        ".text": 135
                    }
                },
                {
                    "module": "rtos/rtx",
                    "size": {
                        ".data": 20,
                        ".bss": 6870,
                        ".text": 5861
                    }
                },
                {
                    "module": "targets/TARGET_Freescale",
                    "size": {
                        ".data": 12,
                        ".bss": 384,
                        ".text": 8382
                    }
                },
                {
                    "summary": {
                        "total_flash": 91947,
                        "static_ram": 14116,
                        "stack": 0,
                        "heap": 24576,
                        "total_ram": 38692
                    }
                }
            ]
        }
    ]
}
```

**Comment by jupe** [comment]
Looks much better 👍. small notes:
* library_config contains paths without relative path prefix `./`
* Was there memory_usage already in json file? its enough to set relative path for it
* where `id` come from?
* could you add mbed-cli version number, as well as toolchain version
* what about git details - mbed-os repository as well as application and its modules

by the wqy. how this looks when compiling "normal application" ? is there also libraries details?

**Comment by theotherjimmy** [comment]
>date

I was planning to add build date. 👍 

> library_config contains paths without relative path prefix ./

The paths are still relative paths. would you like the ./?

> Was there memory_usage already in json file? its enough to set relative path for it

Nope.

> where id come from?

This is the same ID that is used by the testing infrastructure. Beyond that I don't know.

> could you add mbed-cli version number, as well as toolchain version

mbed-cli should add it's own version. Toolchains currently do not have a way of doing version detection. I'll have to add that.

>what about git details - mbed-os repository as well as application and its modules

mbed-cli should add that too.

At the moment, I'm trying to get the information for you from the mbed tools. I'll add the mbed-cli metadata in a bit.

**Comment by jupe** [comment]
do we have PR already somewhere ?

**Comment by jupe** [comment]
> "memory_usage": ..

We have already file which contains this information, doesn't we ? called `<build>_map.json` . Maybe there could be just reference (relative path) for that file.

**Comment by theotherjimmy** [comment]
@jupe 

>do we have PR already somewhere?

I want to clean that branch up before submitting it as a PR. I would block it ATM as it's written with very poor style.

>We have already file which contains this information, doesn't we ? called `<build>_map.json` . Maybe there could be just reference (relative path) for that file.

Possibly, but when generating that file, we don't store the location of that file anywhere in the python object, so it's easier to dump the contents again. I agree that we should dump something once, as it feels more efficient. You have to remember that we are still talking about a file that is smaller that most file system's cluster size, so any optimization at this point is probably premature.

`<rant>`

I would really like to re-factor the current test reporting functionality and this proposition to use the same reporting mechanism. That way we can deduplicate these sorts of efforts and bug fixes that affect one side get picked up by the others.

`</rant>`

**Comment by jupe** [comment]
@theotherjimmy any news ?

**Comment by theotherjimmy** [comment]
Nope. Let's get this done soon.

**Comment by jupe** [comment]
PR https://github.com/ARMmbed/mbed-os/pull/4110 will cover first part of this issue

**Comment by jupe** [comment]
@bridadan any chance to extend build-data with git details? its very important because otherwise we doesn't have any exact information about what is actual code in build. There should be git hashes&possible tags for each repository used in build.

**Comment by bridadan** [comment]
@jupe I'm wondering how we can do this without passing ALL of this information to the build tools, seems like it's definitely gotta be in a file. What if we augmented the `mbed ls` command of mbed CLI to output all of this data?

**Comment by jupe** [comment]
I did think that mbed cli has already most of these git details, isn't it? or at least easy to fetch using cli functions it has already.. ? `mbed ls` sounds too close `mbedls` for me but idea is fine for me - BUT i dont want to call multiple times these tools to get all this data.. now building produce initial file already and doesn't make sense if i have to call another time tools to fullfill that

**Comment by bridadan** [comment]
> I did think that mbed cli has already most of these git details, isn't it

Yes it does!

> `mbed ls` sounds too close `mbedls` for me but idea is fine for me

Agreed, though that's probably a topic for another time 😄 

> i dont want to call multiple times these tools to get all this data.. now building produce initial file already and doesn't make sense if i have to call another time tools to fullfill that

Also makes sense. Perhaps we could make mbed CLI (when provided a global config option OR an argument flag) output a file detailing the git details in either root directory or the build directory ahead of time. Then the build tools could slurp this up and include it in the build directory.

@theotherjimmy How do you feel about the build tools when they detect a JSON file called `extra_build_data.json` or something in the project directory to do a basic JSON key-value merge of all the values? This way it's general and can be used for other purposes if need be.

**Comment by theotherjimmy** [comment]
@bridadan We could do that, but we already have an option to specify the location of the build data file. instead, why don't we just create (or add) the build data to that file? I don't want to have to explicitly name this when we already accept an option for it.

**Comment by bridadan** [comment]
@theotherjimmy that's fine with me too!

**Comment by jupe** [comment]
I propose to extend/create existing file with git details. `--build-json` is already there so `mbed CLI` could pick it right after/before compile call and extend it... When we could get this ?
